# Unix submit description file
arguments               = $(Item)
executable              = /storage/gpfs_data/neutrino/users/gi/sand-physics/condor_submission/executables/AnalyseEDepSim.sh
log                     = /storage/gpfs_data/neutrino/users/gi/sand-physics/condor_submission/logs/AnalyseEDepSim.log
output                  = /storage/gpfs_data/neutrino/users/gi/sand-physics/condor_submission/logs/AnalyseEDepSim.out
error                   = /storage/gpfs_data/neutrino/users/gi/sand-physics/condor_submission/logs/AnalyseEDepSim.err
should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT
queue from seq 0 9 |